print("Welcome to the Numpy Analyzer")
print("-------------------------------------------------------------")
print("Choose an option:")
print("1.Create a Numpy Array")
print("2.perform mathematical operations")
print("3.combine and spilit arary")
print("4.Search,sort or filter array")
print("5.Compute Aggregates and statistics")
print("6.Exit")

print("1.array creation")
choice=int(input("enter your choice:"))
print("select the type of array to create")
print("1.1D array")
print("2.2D array")
print("3.3D array")
choice=int(input("enter your choice:"))
number=int(input("enter the number of rows:"))
number=int(input("enter the number of colomn:"))
num1=list(map(int,input("enter 6 element of the array seperated by space:").split()))
print("Array created successfully")

import numpy as np
array=np.array([[10,20,30],
            [40,50,60]])
print(array)
print("Choose an operation")
print("1.indexing")
print("2.slicing")
print("3.Go back")
choice=int(input("enter your choice:"))
number=(input("enter the row range(start:end:"))
number=(input("enter the column range(start:end:"))

print("2.Sliced array")
array=np.arange(10, 70, 10).reshape(2,3)
print(array)
print(array[0:2,1:3])

print("3.Mathematical operations")
print("1.Addition")
print("1.Subtraction")
print("1.Multiplication")
print("1.Division")
choice=int(input("enter your choice:"))
num=list(map(int,input("Enter the same size array element(6 element seperated by space:").split()))
print("Original Array")
array1=np.array([[10,20,30],
             [40,50,60]])
print(array1)
print("Second array")
array2=np.array([[5,5,5],
                [5,5,5]])
print(array2)
result=array1+array2
print("Result of addition")
print(result)

print("4.combine or spilit array")
print("choose an option")
print("1.combined arrays")
print("2.split arrays")
choice=int(input("enter your choice:"))
nums = list(map(int, input("Enter 6 elements separated by space: ").split()))
array1=np.array([[10,20,30],
             [40,50,60]])
print(array1)

array2=np.array([[1,2,3],
                [4,5,6]])
print(array2)
print("combined array (verticle stack):" )
combined=np.concatenate((array1,array2) , axis=0)
print(combined)

print("4.Search , sort & Filter")
print("choose an option")
print("1.Search the value")
print("2.sort the arrays")
print("3.filtered value")
choice=int(input("enter your choice:"))
print("Original array")
array1=np.array([[10,20,30],
             [40,50,60]])
print(array1)
print("2.Sorted array")
print("\nRow-wise Sorted Array:")
sorted_array=np.sort(array1,axis=1)
print(sorted_array)

print("5.Choose an aggregate/statistical operations:")
print("1.sum")
print("2.mean")
print("3.median")
print("standard deviation")
print("variance")
choice=int(input("enter your choice:"))
print("Original array:")
array1=np.array([[10,20,30],
             [40,50,60]])
print(array1)
median_array=np.median(array1)
print("Median of Array",median_array)

print("6.exit")
print("Choose an option:")
print("1.Create a Numpy Array")
print("2.perform mathematical operations")
print("3.combine and spilit arary")
print("4.Search,sort or filter array")
print("5.Compute Aggregates and statistics")
print("Exit")
choice=int(input("enter your choice:"))

print("Thank you for using the numpy-analyzer! goodbye!")